# .github/workflows/stop-railway.yml
name: Stop Railway on Saturday

on:
  schedule:
    - cron: '0 14 * * 5' # 금요일 24시 KST = 금요일 15시 UTC
  workflow_dispatch:

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - name: Stop Railway Service
        run: |
          curl -X POST https://backboard.railway.app/graphql \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_API_TOKEN }}" \
            -d '{"query":"mutation { stopEnvironment(id: \"${{ secrets.RAILWAY_ENV_ID }}\") { id } }"}'